// Generated by Wrangler on Wed Sep 11 2024 18:48:19 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	LINE_MESSAGING_API_CHANNEL_ID: string;
	LINE_MESSAGING_API_CHANNEL_SECRET: string;
}
